from django.urls import path
from .views import *

urlpatterns = [
    path('api/v1/categories/', CategoryListApiView.as_view()),
    path('api/v1/category/<int:pk>/', CategoryDetailApiView.as_view()),
    path('api/v1/new_category/', CategoryCreateApiView.as_view()),
    path('api/v1/update_category/<int:pk>/', CategoryUpdateApiView.as_view()),
    path('api/v1/delete_category/<int:pk>/', CategoryDeleteApiView.as_view()),
    path('api/v1/products/', ProductListApiView.as_view()),
    path('api/v1/product/<int:pk>/', ProductDetailApiView.as_view()),
    path('api/v1/new_product/', ProductCreateApiView.as_view()),
    path('api/v1/update_product/<int:pk>/', ProductUpdateApiView.as_view()),
    path('api/v1/delete_product/<int:pk>/', ProductDeleteApiView.as_view()),
    path('api/v1/favourite_products/', FavouriteListApiView.as_view()),
    path('api/v1/user_favourite/<int:id>/', UserFavouriteListAPIView.as_view()),
    path('api/v1/add_to_favourite/', FavouriteAddApiView.as_view()),
    path('api/v1/delete_favourite/<int:pk>/', FavouriteDeleteApiView.as_view()),
    path('api/v1/favourite_detail/<int:pk>/', FavouriteDetailApiView.as_view()),
    path('api/v1/user_cart/<int:id>/', UserCartListAPIView.as_view()),
    path('api/v1/cart_list/', OrderListProductApiView.as_view()),
    path('api/v1/cart_detail/<int:pk>/', OrderDetailApiView.as_view()),
    path('api/v1/add_to_cart/', OrderAddApiView.as_view()),
    path('api/v1/cart_delete/<int:pk>/', OrderDeleteApiView.as_view()),
    path('api/v1/order_list/', OrderProductListApiView.as_view()),
    path('api/v1/user_order/<int:id>/', UserOrderAPIView.as_view()),
    path('api/v1/order_detail/<int:pk>/', OrderProductDetailApiView.as_view()),
    path('api/v1/profile_list/', ProfileListApiView.as_view()),
    path('api/v1/profile_detail/<int:pk>/', ProfileDetailApiView.as_view()),
    path('api/v1/profile_edit/<int:pk>/', ProfileUpdateApiView.as_view()),
    path('api/v1/profile_delete/<int:pk>/', ProfileDeleteApiView.as_view()),
    path('api/v1/user_profile/<int:id>/', UserProfileAPIView.as_view()),
    path('api/v1/shipping_addresses/', ShippingAddressApiView.as_view()),
]
