# Generated by Django 5.1.4 on 2024-12-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(default='Не указано', max_length=10, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(default='Не указано', max_length=10, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(default='Не указано', max_length=10, verbose_name='Ширина'),
        ),
    ]
