# Generated by Django 5.1.4 on 2024-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0005_product_depth_product_height_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accumulator',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Аккумулятор'),
        ),
        migrations.AddField(
            model_name='product',
            name='back_camera',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='technology',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Технологии'),
        ),
    ]
