# Generated by Django 5.1.4 on 2024-12-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0006_product_accumulator_product_back_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accumulator',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Аккумулятор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_camera',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, default='Не указано', max_length=10, null=True, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, default='Не указано', max_length=10, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technology',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, default='Не указано', max_length=10, null=True, verbose_name='Ширина'),
        ),
    ]
