# Generated by Django 5.1.1 on 2025-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0012_alter_profile_options_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка'),
        ),
    ]
