# Generated by Django 5.1.6 on 2025-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0013_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_camera',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Задняя камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Гарантия'),
        ),
    ]
